# Author: IrishMaestro <github.com/irishmaestro>

# Syntax highlighting
"type" = { fg = "crystal_blue" }
"type.builtin" = { fg = "crystal_blue" }
"constructor" = { fg = "green" }
"constant" = { fg = "hazmat_yellow" }
"string" = { fg = "crystal_blue" }
"string.regexp" = { fg = "orange" }
"string.special" = { fg = "yellow" }
"comment" = { fg = "teddy_bear_pink", modifiers = ["slow_blink", "italic"] }
"variable" = { fg = "element_green" }
"variable.parameter" = { fg = "hazmat_yellow" }
"label" = { fg = "vapor_yellow" }
"punctuation" = { fg = "green" }
"keyword" = { fg = "green" }
"keyword.control" = { fg = "teddy_bear_pink" }
"keyword.directive" = { fg = "teddy_bear_pink" }
"operator" = { fg = "hazmat_yellow" }
"function" = { fg = "cash_green", modifiers = ["bold"] }
"tag" = { fg = "crystal_blue" }
"namespace" = { fg = "hazmat_yellow" }
"markup.heading" = { fg = "hazmat_yellow" }
"markup.list" = { fg = "yellow" }
"markup.raw.block" = { bg = "gray", fg = "orange" }
"markup.link.url" = { fg = "crystal_blue" }
"markup.link.text" = { fg = "yellow" }
"markup.link.label" = { fg = "green" }
"markup.quote" = { fg = "yellow" }
"diff.plus" = { fg = "green" }
"diff.minus" = { fg = "red" }
"diff.delta" = { fg = "green" }

# Interface
"ui.background" = { bg = "background" }
"ui.cursor" = { bg = "crystal_blue", fg = "background" }
"ui.cursor.match" = { fg = "hazmat_yellow" }
"ui.linenr" = { fg = "crystal_blue" }
"ui.linenr.selected" = { fg = "green" }
"ui.statusline" = { fg = "crystal_blue", bg = "black" } 
"ui.cursorline" = { bg = "background" }
"ui.popup" = { fg = "crystal_blue", bg = "background" }
"ui.window" = { fg = "green" }
"ui.help" = { fg = "crystal_blue", bg = "background"}
"ui.text" = { fg = "crystal_blue" }
"ui.text.focus" = { bg = "background", fg = "teddy_bear_pink" }
"ui.text.info" = { fg = "crystal_blue" }
"ui.virtual.whitespace" = { fg = "dark_gray" }
"ui.virtual.ruler" = { bg = "background" }
"ui.menu" = { fg = "crystal_blue", bg = "background" }
"ui.menu.selected" = { bg = "hazmat_yellow", fg = "background" }
"ui.selection" = { bg = "dark_gray" }
"warning" = { fg = "vapor_yellow" }
"error" = { fg = "chili_powder_red", modifiers = ["bold"] }
"info" = { fg = "crystal_blue", modifiers = ["bold"] }
"hint" = { fg = "crystal_blue", modifiers = ["bold"] }
"diagnostic"= { fg = "chili_powder_red", modifiers = ["underlined"] }
"diagnostic.info"= { fg = "crystal_blue", modifiers = ["underlined"] }
"diagnostic.warning"= { fg = "vapor_yellow", modifiers = ["underlined"] }
"diagnostic.error"= { fg = "chili_powder_red", modifiers = ["underlined"] }
"ui.bufferline" = { fg = "gray", bg = "background" }
"ui.bufferline.active" = { fg = "foreground", bg = "dark_gray" }

"special" = { fg = "teddy_bear_pink" }

[palette]
background = "#000000"   
foreground = "#cccccc"
black = "#121212"
blue = "#59c2ff"
dark_gray = "#2d3640"
cyan = "#73b8ff"
gray = "#5c6773"
green = "#009669"
orange = "#ff8f40"
red = "#f07178"
yellow = "#fefd08"
hazmat_yellow = "#f7b90c"
vapor_yellow = "#cecd19"
teddy_bear_pink = "#bd5173"
crystal_blue = "#32c9fa"
cash_green = "#00ff80"
element_green = "#186800"
chili_powder_red = "#c32101"